config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "logs/registrations"
  }
  get 'reservation/index'
  get 'rooms/index'

  post 'users/new'
  root to: 'users#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users
  resources :rooms
  resources :reservations do
    collection do
      post :confirm
      end
    end

  get '/profile', to: 'users#profile'
  get '/account', to: 'users#account'
  get '/profile/edit', to: 'users#edit'
  patch '/profile', to:'users#profile'
  post '/profile', to:'users#profile'
  get '/booking', to:'rooms#booking'
  post '/booking', to:'rooms#booking'
  get '/own', to:'rooms#own'
  get '/result', to:'rooms#result'
  patch '/account', to:'users#account'
  patch '/reservations', to:'reservations#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  mount_uploader :img, ImageUploader
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true, on: :create
  validates :password, presence: true, on: :create
  validates :password_confirmation, presence: true,  on: :create

  has_many :rooms
  has_many :reservations

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = current_user
    @q = Room.ransack(params[:q])
    @rooms = @q.result(distinct: true)
  end

  def new
    @user = User.new
  end

  def show

  end

  def update
    @user = current_user
    if @user.update(uesr_params)
      redirect_to profile_path
    else
      render"edit"
    end
  end

  def account
    @user = current_user
  end

  def profile
    @user = current_user
  end

  def edit
    @user = current_user
  end

  private
  def uesr_params
    params.require(:user).permit(:name,:introduction,:img)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/account.html.erb
<div class="profile_body">
  <div class="profile_title">
  <h1>設定</h1>
  </div>
  <div class="profile_container">
      <ul class="choice_box">
        <li><%= link_to"アカウント"%></li>
        <li><%= link_to"プロフィール",profile_path%></li>
      </ul>
      <div class="edit_box">
        <div class="edit_bar">
          <p>アカウント</p>
          <p class="edit_link"><%=link_to"編集",edit_user_registration_path%></p>
        </div>
        <table class="setting_table">
          <tr>
            <th class="th_title">メールアドレス</th>
            <td><%= @user.email%></td>
          </tr>
          <tr>
            <th class="th_title">パスワード</th>
            <td>*********</td>
          </tr>
        </table>
    </div>
  </div>

<div>

app/views/users/edit.html.erb
<div class="profile_body">
  <div class="profile_title">
  <h1>設定</h1>
  </div>
  <div class="profile_container">
      <ul class="choice_box">
        <li><%= link_to"アカウント",account_path%></li>
        <li><%=link_to"プロフィール",profile_path%></li>
      </ul>
      <div class="edit_box">
        <div class="edit_bar">
          <p>プロフィール</p>
        </div>
        <%= form_with model: @user do |f|%>
          <table class="edit_table">
          <%= render "shared/error", obj: @user %>
            <tr>
              <th class="th_title"><%=f.label:"アイコン画像"%></th>
              <td>
                  <% if @user.img?%>
                  <%= image_tag @user.img.thumb.url, class:"rounded-circle size100✖️100" %>
                  <% else %>
                  <%= image_tag("default-avatar.png")%>
                  <% end %>
                  <%= f.file_field :img %>
              </td>
            </tr>
            <tr>
              <th class="th_title"><%= f.label :name,"名前"%></th>
              <td><%= f.text_field :name,class:"edit_field" %></td>
            </tr>
            <tr>
              <th class="th_title"><%= f.label :introduction ,"自己紹介" %></th>
              <td><%= f.text_area :introduction,class:"edit_area" %></td>
            </tr>
          </table>
          <div class="edit_btn_box">
            <%= f.submit"保存",class:"edit_submit"%>
            <%= link_to"キャンセル",profile_path,class:"edit_cansel_btn"%>
          </div>
          <% end %>
        </table>
    </div>
  </div>

<div>

app/views/users/index.html.erb
<div>


<div class="index_backimg">
  <div class="index_search_area">
  <h2 class="index_title">Potepan Shareで<br>まだ体験したことのない旅をしよう</h2>
    <%= search_form_for @q, url:result_path, class:"index_search_box" do |f|%>
        <%= f.label"施設名・キーワードから探す", class:"index_search_text"%><br>
        <%= f.search_field :name_or_introduction_or_address_cont, placeholder:"施設名・キーワードを入力", class:"index_search_field"%>
        <%= f.submit class:"index_submit" %>
    <% end %>
  </div>

</div>

<div class="index_item_box">


  <h3 class="index_subtitle">エリアから探す</h3>
  <div class="index_item_container">
    <div>
      <p class="image_title">東京都</p>
      <%= link_to image_tag("tohyo_image.jpg", class:"index_image"), result_path(q:{address_cont:"東京"})%>
    </div>
    <div>
      <p class="image_title">大阪府</p>
      <%= link_to image_tag("osaka_image.jpg", class:"index_image"), result_path(q:{address_cont:"大阪"})%>
    </div>
    <div>
      <p class="image_title">京都府</p>
      <%= link_to image_tag("kyoto_image.jpg", class:"index_image"), result_path(q:{address_cont:"京都"})%>
    </div>
    <div>
      <p class="image_title">札幌市</p>
      <%= link_to image_tag("sapporo_image.jpg", class:"index_image"), result_path(q:{address_cont:"札幌"})%>
    </div>
  </div>


</div>

app/views/users/profile.html.erb
<div class="profile_body">
  <div class="profile_title">
  <h1>設定</h1>
  </div>
  <div class="profile_container">
      <ul class="choice_box">
        <li><%= link_to"アカウント",account_path%></li>
        <li><%= link_to"プロフィール",profile_path%></li>
      </ul>
      <div class="edit_box">
        <div class="edit_bar">
          <p>プロフィール</p>
          <p class="edit_link"><%=link_to"編集",profile_edit_path %></p>
        </div>
        <table class="setting_table">
          <tr>
            <th class="th_title">アイコン画像</th>
            <td>
            <% if @user.img? %>
            <%= image_tag @user.img.thumb.url, class:"rounded-circle size100✖️100" %>
            <% else %>
            <%= image_tag "default-avatar.png", class:"size100✖️100"%>
            <% end %>
            </td>
          </tr>
          <tr>
            <th class="th_title">名前</th>
            <td><%= @user.name %></td>
          </tr>
          <tr>
            <th class="th_title">自己紹介</th>
            <td><%= @user.introduction %></td>
          </tr>
        </table>
    </div>
  </div>

<div>