config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "logs/registrations"
  }
  get 'reservation/index'
  get 'rooms/index'

  post 'users/new'
  root to: 'users#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users
  resources :rooms
  resources :reservations do
    collection do
      post :confirm
      end
    end

  get '/profile', to: 'users#profile'
  get '/account', to: 'users#account'
  get '/profile/edit', to: 'users#edit'
  patch '/profile', to:'users#profile'
  post '/profile', to:'users#profile'
  get '/booking', to:'rooms#booking'
  post '/booking', to:'rooms#booking'
  get '/own', to:'rooms#own'
  get '/result', to:'rooms#result'
  patch '/account', to:'users#account'
  patch '/reservations', to:'reservations#index'
end

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
<% obj.errors.full_messages.each do |message| %>
  <ul>
    <li class="error_messege"><%= message %></li>
  </ul>
<% end %>
<% end %>

app/views/shared/_login.html.erb
<header class="header_bar">
  <div class="header_box">
    <h1><%= link_to"Potepan Share",users_path%></h1>
      <label for="toggle" onclick="" for="menuToggle" class="headder_menu">
        <% if @user.img? %>
        <%= image_tag @user.img.thumb.url, class:"rounded-circle size50✖️50"%>
        <% else %>
        <%= image_tag "default-avatar.png",class:"size50✖️50" %>
        <% end %>
        <p class="headder_name"><%= @user.name%></p>
      </label>
  </div>
</header>
<input type="checkbox" id="toggle" autocomplete="off">
<ul class="dropdown_list" id="menu">
  <li class="dropdown_list"><%= link_to"施設の新規登録",new_room_path%></li>
  <li class="dropdown_list"><%= link_to"予約済み一覧", reservations_path%></li>
  <li class="dropdown_list"><%= link_to"登録済み一覧", own_path%></li>
  <li class="dropdown_list"><%= link_to"アカウント設定",account_path%></li>
  <p><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></p>
</ul>

app/views/shared/_login_result.html.erb
<% @rooms.each do |room|%>
  <li class="result_container">
    <div class="result_img_container">
      <% if room.img? %>
      <%= image_tag room.img.thumb.url, class:"result_img"%>
      <% else %>
      <%= image_tag "default-image.png", class:"result_img"%>
      <% end %>
    </div>
    <div class="result_info">
      <p class="result_name"><%= room.name %></p>
      <p><%= room.address%></p>
      <p><%= room.introduction %></p>
      <p class="result_price_all">1名 1泊あたり/<span class="result_price">¥<%= room.price %>〜</span></p>
    </div>
    <%= link_to"詳細はこちら", room, class:"result_detail_btn"%>
  </li>
  <% end %>

app/views/shared/_not_login.html.erb
<header class="header_bar">
<div class="header_box">
  <h1><%= link_to"Potepan Share",users_path%></h1>
  <div class="not_login_box">
    <p class="not_login_btn"><%= link_to"ログイン",new_user_session_path%></p>
    <p class="not_new_btn"><%= link_to"新規登録",new_user_registration_path %></p>
  </div>
</div>
</header>

app/views/shared/_not_login_result.html.erb
<% @rooms.each do |room|%>
  <li class="result_container">
    <div class="result_img_container">
      <% if room.img? %>
      <%= image_tag room.img.thumb.url, class:"result_img"%>
      <% else %>
      <%= image_tag "default-image.png", class:"result_img"%>
      <% end %>
    </div>
    <div class="result_info">
      <p class="result_name"><%= room.name %></p>
      <p><%= room.address%></p>
      <p><%= room.introduction %></p>
      <p class="result_price_all">1名 1泊あたり/<span class="result_price">¥<%= room.price %>〜</span></p>
    </div>
    <%= link_to"ログインをして詳細を見る", new_user_session_path, class:"result_detail_btn"%>
  </li>
  <% end %>