config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "logs/registrations"
  }
  get 'reservation/index'
  get 'rooms/index'

  post 'users/new'
  root to: 'users#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users
  resources :rooms
  resources :reservations do
    collection do
      post :confirm
      end
    end

  get '/profile', to: 'users#profile'
  get '/account', to: 'users#account'
  get '/profile/edit', to: 'users#edit'
  patch '/profile', to:'users#profile'
  post '/profile', to:'users#profile'
  get '/booking', to:'rooms#booking'
  post '/booking', to:'rooms#booking'
  get '/own', to:'rooms#own'
  get '/result', to:'rooms#result'
  patch '/account', to:'users#account'
  patch '/reservations', to:'reservations#index'
end

app/models/reservation.rb
class Reservation < ApplicationRecord

  belongs_to :user
  belongs_to :room

  validates :check_in_at, presence:true
  validates :check_out_at, presence:true
  validates :persons, presence:true, numericality: {only_integer: true, greater_than_or_equal_to: 1}
  validate :today_after
  validate :check_out_at_after

  def today_after
    errors.add(:check_in_at,"は本日以降の日付を選択してください") if check_in_at.nil? || check_in_at < Date.today
  end
  
  def check_out_at_after
    errors.add(:check_out_at,"はチェックイン日より後の日付を選択してください") if check_in_at.nil? || check_out_at.nil? || check_out_at <= check_in_at
  end 

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @user = current_user
    @reservations = @user.reservations
    @room = Room.all
  end

  def show
    @user = current_user
    @reservations = @user.reservations
    @room = Room.all
  end

  def new 
  end

  def confirm
    @reservation = Reservation.new(reservation_parms)
    @user = current_user
      if @reservation.valid? 
        @room = @reservation.room
        days_seconds = @reservation.check_out_at-@reservation.check_in_at
        @reservation.days = (days_seconds/1.days).floor
        @reservation.total_price = @reservation.persons*@room.price*@reservation.days 
      else
        @room = @reservation.room
        render"rooms/show"
      end
      
  end

  def create
    @reservation = Reservation.new(reservation_parms)
    @user = current_user
    @reservation.save
    redirect_to :reservations
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def booking

  end

  private
  def reservation_parms
    params.require(:reservation).permit(:persons, :days, :room_id, :check_in_at, :check_out_at, :total_price, :user_id)
  end
  
end

app/helpers/reservation_helper.rb
module ReservationHelper
end

app/views/reservations/confirm.html.erb
<div class="confirm_box">
  <h2 class="confirm_title">予約内容の確認</h2>
  <table class="confirm_table">
    <tr class="confirm_tr">
      <th>チェックイン</th>
      <td><%= l @reservation.check_in_at, format: :short %></td>
    </tr>
    <tr class="confirm_tr">
      <th>チェックアウト</th>
      <td><%= l @reservation.check_out_at, format: :short %></td>
    </tr>
    <tr class="confirm_tr">
      <th>日数</th>
      <td><%= @reservation.days%></td>
    </tr>
    <tr class="confirm_tr">
      <th>人数</th>
      <td><%= @reservation.persons%></td>
    </tr>
    <tr class="confirm_tr">
      <th>総支払額</th>
      <td>¥<%= @reservation.total_price %><span>（お一人様一泊あたり/<%=@room.price%>)</span></td>
    </tr>
  </table>



<%= form_with model: @reservation, url:reservations_path, local: true do |f|%>
  <%= f.hidden_field :check_in_at %>
  <%= f.hidden_field :check_out_at %>
  <%= f.hidden_field :days %>
  <%= f.hidden_field :persons%>
  <%= f.hidden_field :total_price %>
  <%= f.hidden_field :user_id%>
  <%= f.hidden_field :room_id%>
  <%= f.submit"予約を完了する", class:"confirm_submit" %>
<% end %>
<%= link_to"キャンセル", room_path(@room), class:"confirm_btn" %>
</div>

app/views/reservations/index.html.erb
<div class="index_body">
<div class="index_box">
  <h2 class="reserve_index_title">予約済み一覧</h2>
    <table class="index_table">
      <thead>
        <tr>
          <th class="index_thead">画像</th>
          <th class="index_thead">施設名</th>
          <th class="index_thead">紹介文</th>
          <th class="index_thead">総支払額</th>
          <th class="index_thead">チェックイン</th>
          <th class="index_thead">チェックアウト</th>
          <th class="index_thead">予約確定日時</th>
        </tr>
      </thead>
      <tbody>
        <% @reservations.each do |post|%>
        <% @room = post.room %>
          <tr>
            <th class="index_th">
              <% if @room.img? %>
              <%= image_tag @room.img.thumb.url, class:"size100✖️100"%>
              <% else %>
              <%= image_tag "default-image.png", class:"hotel_img"%>
              <% end %>
            </th>
            <th class="index_th"><%= link_to"#{@room.name}",room_path(@room.id) %></th>
            <th class="index_th"><%= @room.introduction %></th>
            <th class="index_th">¥<%= post.total_price %></th>
            <th class="index_th"><%= l post.check_in_at, format: :short %></th>
            <th class="index_th"><%= l post.check_out_at, format: :short %></th>
            <th class="index_th"><%= l post.created_at %></th>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>
</div>