config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "logs/registrations"
  }
  get 'reservation/index'
  get 'rooms/index'

  post 'users/new'
  root to: 'users#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users
  resources :rooms
  resources :reservations do
    collection do
      post :confirm
      end
    end

  get '/profile', to: 'users#profile'
  get '/account', to: 'users#account'
  get '/profile/edit', to: 'users#edit'
  patch '/profile', to:'users#profile'
  post '/profile', to:'users#profile'
  get '/booking', to:'rooms#booking'
  post '/booking', to:'rooms#booking'
  get '/own', to:'rooms#own'
  get '/result', to:'rooms#result'
  patch '/account', to:'users#account'
  patch '/reservations', to:'reservations#index'
end

app/models/room.rb
class Room < ApplicationRecord
  mount_uploader :img, ImageUploader
  validates :name, presence:true
  validates :introduction, presence:true
  validates :price, presence:true, numericality: {greater_than_or_equal_to:1}
  validates :address, presence:true
  
  
  belongs_to :user
  has_many :reservations
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @user = current_user
    @reservations = Reservation.all
  end

  def new
    @user = current_user
    @room = Room.new
  end

  def create
    @user = current_user
    @room = Room.new(room_parms)
    @room.poster = current_user.id
    if @room.save
      redirect_to room_url(id: @room.id)
    else
      render"new"
    end
  end


  def show
    @reservation = Reservation.new
    @user = current_user
    @room = Room.find(params[:id])
  end

  def edit
    @user = current_user
    @room = Room.find(params[:id])
  end

  def update
    @user = current_user
    @room = Room.find(params[:id])
    if @room.update(room_parms)
      redirect_to :own
    else
      render"edit"
    end

  end

  def destroy

  end

  def own
    @user = current_user
    @room = Room.all
    @rooms = @user.rooms
  end

  def result
    @user = current_user
    @room = Room.all
    @q = Room.ransack(params[:q])
    @rooms = @q.result(distinct: true)
  end

  private
  def room_parms
    params.require(:room).permit(:name,:introduction,:img,:price,:address,:user_id,:persons,:days, :total_price)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/edit.html.erb
<div class="room_new_body">
  <div class="new_form">
    <h2 class="room_new_title">施設情報編集</h2>
    <%= form_with model: @room do |f| %>
        <table class="new_table">
          <tr>
            <th class="new_th"><%= f.label:name, "施設名"%><span class="required">*</span></th>
            <td class="new_td"><%= f.text_field:name,class:"new_field", placeholder:"ルーム名を入力"%></td>
          </tr>
          <tr>
            <th class="new_th"><%= f.label:introduction, "施設詳細"%><span class="required">*</span></th>
            <td class="new_td"><%= f.text_area:introduction,class:"new_area", placeholder:"施設詳細を入力"%></td>
          </tr>
          <tr>
            <th class="new_th"><%= f.label:price, "料金"%><span class="required">*</span></th>
            <td class="new_td"><%= f.text_field:price,class:"new_field", placeholder:"一日あたりの料金を入力"%></td>
          </tr>
          <tr>
            <th class="new_th"><%= f.label:address, "住所"%><span class="required">*</span></th>
            <td class="new_td"><%= f.text_field:address, class:"new_field", placeholder:"住所を入力" %></td>
          </tr>
          <tr>
            <th class="new_th"><%= f.label:img, "施設画像"%></th>
            <td class="new_td">
              <%= f.file_field :img %>
            </td>
          </tr>
        </table>
          <%= f.hidden_field :user_id,value:current_user.id%>
        <div class="actions">
        <%= f.submit "保存", class:"new_submit"%>
        <%= link_to"キャンセル",:own, class:"edit_cansel_btn"%>
        </div>
    <% end %>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="room_new_body">
  <div class="new_form">
    <h2 class="room_new_title">新規登録</h2>
    <%= render"shared/error", obj:@room, class:"error_messege"%>
    <%= form_with model: @room do |f| %>
        <table class="new_table">
          <tr>
            <th class="new_th"><%= f.label:name, "施設名"%><span class="required">*</span></th>
            <td class="new_td"><%= f.text_field:name,class:"new_field", placeholder:"ルーム名を入力"%></td>
          </tr>
          <tr>
            <th class="new_th"><%= f.label:introduction, "施設詳細"%><span class="required">*</span></th>
            <td class="new_td"><%= f.text_area:introduction,class:"new_area", placeholder:"施設詳細を入力"%></td>
          </tr>
          <tr>
            <th class="new_th"><%= f.label:price, "料金"%><span class="required">*</span></th>
            <td class="new_td"><%= f.text_field:price,class:"new_field", placeholder:"一日あたりの料金を入力"%></td>
          </tr>
          <tr>
            <th class="new_th"><%= f.label:address, "住所"%><span class="required">*</span></th>
            <td class="new_td"><%= f.text_field:address, class:"new_field", placeholder:"住所を入力" %></td>
          </tr>
          <tr>
            <th class="new_th"><%= f.label:img, "施設画像"%></th>
            <td class="new_td">
              <%= f.file_field :img %>
            </td>
          </tr>
        </table>
          <%= f.hidden_field :user_id,value:current_user.id%>
        <div class="actions">
        <%= f.submit "保存", class:"new_submit"%>
        <%= link_to"キャンセル",users_path, class:"edit_cansel_btn"%>
        </div>
    <% end %>
  </div>
</div>

app/views/rooms/own.html.erb
<div class="own_body">
  <div class="own_box">
    <h2 class="own_title">登録済み一覧</h2>
      <table class="own_table">
        <thead>
          <tr>
            <th class="own_thead">画像</th>
            <th class="own_thead">施設名</th>
            <th class="own_thead">紹介文</th>
            <th class="own_thead">料金</th>
            <th class="own_thead">作成日</th>
          </tr>
        </thead>
        <tbody>
          <% @rooms.each do |post|%>
            <tr>
              <th class="own_th">
                <% if post.img? %>
                <%= image_tag post.img.thumb.url, class:"size100✖️100"%>
                <% else %>
                <%= image_tag "default-image.png", class:"hotel_img"%>
                <% end %>
              </th>
              <th class="own_th"><%= link_to"#{post.name}",post%></th>
              <th class="own_th"><%= post.introduction%></th>
              <th class="own_th">¥<%= post.price%></th>
              <th class="own_th"><%= l post.created_at, format: :short%></th>
            </tr>
          <% end %>
        </tbody>
      </table>
  </div>
</div>

app/views/rooms/result.html.erb
<div class="result_body">
<p class="result_text"><%=@rooms.size%>件が見つかりました。</p>
  <ul class="result_box">
  <% if user_signed_in? %>
  <%= render "shared/login_result"%>
  <% else %>
  <%= render "shared/not_login_result"%>
  <% end %>
  </ul>
</div>

app/views/rooms/show.html.erb
<div class="detail_body">

  <div class="detail_box">
    <div class="link_box">
      <%= link_to"←戻る",:back,class:"link_text"%>
      <%= link_to"編集", edit_room_path(@room.id),class:"link_text"%>
    </div>
    <div class="detail_info_box">
      <% if @room.img? %>
      <%= image_tag @room.img.thumb.url,class:"detail_img_container"%>
      <% else %>
      <%= image_tag("default-image.png",class:"detail_img_container")%>
      <% end %>
      <div class="detail_info_container">
        <p class="info_name"><%= @room.name %></p>
        <p class="info_price">1泊 1名あたり/<span class="room_price">¥<%= @room.price %></span>〜</p>
        <p class="info_introduction"><%= @room.introduction%></p>
      </div>
    </div>

    <div class="reserve_box">
      <%= form_with model: @reservation, local:true, url:confirm_reservations_path(@reservation), method: :post do |f| %>
          <%= render"shared/error", obj:@reservation, class:"error_messege"%>
        <div class="show_form_box">
          <div class="show_field">
            <%= f.label"チェックイン" %><br>
            <%= f.date_field :check_in_at, class:"show_field"%>
          </div>
          <div class="show_field">
            <%= f.label"チェックアウト" %><br>
            <%= f.date_field :check_out_at, class:"show_field" %>
          </div>
          <div class="show_field">
            <%= f.label"人数"%><br>
            <%= f.text_field :persons,placeholder:'人数', class:"show_field"%>
          </div>
        </div>
        <%= f.hidden_field :room_id, value: @room.id%>
        <%= f.hidden_field :user_id, value: @user.id%>
        <%= f.hidden_field :total_price %>
        <%= f.submit"予約する",class:"edit_submit"%>
      <% end %>
    </div>

  </div>

</div>